config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#index", as: "root"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete", as: "logout"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  post "/dyna_forms/:id/publish", to: "dyna_forms#publish", as: :dyna_form_publish
  post "/dyna_forms/:id/unpublish", to: "dyna_forms#unpublish", as: :dyna_form_unpublish
  post "/dyna_forms/:id/details", to: "dyna_forms#details", as: :dyna_form_details
  get "/dyna_forms/:id/take_survey", to: "dyna_forms#take_survey", as: :take_survey
  post "/dyna_forms/:id/results", to: "dyna_forms#results", as: :dyna_form_results
  get "/published_surveys", to: "dyna_forms#published_surveys", as: :published_surveys

  delete "form_inputs/:id", to: "form_inputs#destroy", as: :form_input_delete
  post "form_inputs/:id/edit",to: "form_inputs#edit", as: :form_input_edit

  post "submitted_forms/build_survey", to: "submitted_forms#build_survey"
  post "submitted_forms/:id/save_progress", to: "submitted_forms#save_progress", as: :submitted_form_response_save_progress
  resources :submitted_forms, only: [:show]

  resources :dyna_forms do
    resources :form_inputs, except: [:destroy]
    post 'form_inputs/sample', to: 'form_inputs#sample', as: "form_inputs_sample"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"

end

app/controllers/dyna_forms_controller.rb
class DynaFormsController < ApplicationController
  before_action :redirect_if_not_logged_in, except: [:index, :published_surveys, :take_survey]
  before_action :set_dyna_form, except: [:index, :published_surveys, :new, :create, :take_survey]

  layout "application_no_nav", only: :take_survey
  # login_url
  def new
  end

  def details
    partial_path = @dyna_form.locked? ? "preview" : "dyna_form_with_inputs"
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          "user_dyna_form_window",
          partial: "dyna_forms/#{partial_path}",
          locals: {dyna_form: @dyna_form}
        )}
    end
  end

  def take_survey
    @dyna_form = DynaForm.published.find_by(id: params[:id])
  end

  def published_surveys
    @dyna_forms = DynaForm.where(published: true)
  end

  def publish
    updateable = @dyna_form.form_inputs.any? && !@dyna_form.published
    respond_to do |format|
      format.turbo_stream do
        if updateable && @dyna_form.publish
          render turbo_stream: turbo_stream.replace(
            "flash_message",
            partial: "flash_message",
            locals: {message: "#{@dyna_form.title} has been published!", status: "success"}
          )
        else
          render turbo_stream: turbo_stream.replace(
            "flash_message",
            partial: "flash_message",
            locals: {message: "#{@dyna_form.title} cannot be published.", status: "error"}
          )
        end
      end
    end
  end

  def unpublish
    if @dyna_form.unpublish
      render turbo_stream: turbo_stream.replace(
        "flash_message",
        partial: "flash_message",
        locals: {message: "#{@dyna_form.title} has been unpublished.", status: "success"}
      )
    else
      render turbo_stream: turbo_stream.replace(
        "flash_message",
        partial: "flash_message",
        locals: {message: "#{@dyna_form.title} cannot be unpublished", status: "error"}
      )
    end
  end

  def results
    @submitted_data, @headers = @dyna_form.completed_pivot_table
    @pending_data, @headers = @dyna_form.pending_pivot_table
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "user_dyna_form_window",
          partial: "dyna_forms/results",
          locals: {submitted_data: @submitted_data, pending_data: @pending_data, headers: @headers}
        )
      end
    end
  end

  def create
    @dyna_form = Current.user.dyna_forms.new(dyna_form_params)
    respond_to do |format|
      if @dyna_form.save
        format.turbo_stream {render layout: false}
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            @dyna_form,
            partial: "dyna_forms/form",
            locals: {dyna_form: @dyna_form}
          )}
      end
    end
  end

  def destroy
    @dyna_form.destroy
  end

  private
  def dyna_form_params
    params.require(:dyna_form).permit(:title, :description)
  end

  def set_dyna_form
    @dyna_form = Current.user.dyna_forms.find(params[:id]) if Current.user
  end
end

app/views/dyna_forms/_detail.html.erb
<%= turbo_frame_tag "dyna_form_window" do %>
  <div class="card card-body" id="dyna_form_window">
    <div class="button-container">
      <%= button_to "Edit Title/Description", dyna_form_edit_path(dyna_form), class: 'btn btn-outline-primary button-row' %>
    </div>
    <h4>
      <%= dyna_form.title %>
    </h4>
    <p>
      <%= dyna_form.description %>
    </p>
  </div>
<% end %>

app/views/dyna_forms/_dyna_form.html.erb
<%= turbo_frame_tag dom_id(dyna_form) do %>
  <div class="card card-body">
    <h4><%= dyna_form.title%></h4>
    <p>
      <%= dyna_form.description %>
    </p>
    <% if dyna_form.creator == Current.user && dyna_form.published? %>
      <p>
        Share this url to allow others to take your survey: <%= link_to take_survey_url(dyna_form), take_survey_url(dyna_form), target: "_blank" %>
      </p>
    <% end %>
    <div class="button-row-container">
      <% if dyna_form.creator == Current.user %>
        <% if dyna_form.locked %>
          <%= button_to "Results (#{dyna_form.submitted_forms.count})", dyna_form_results_path(dyna_form), class: "button-row btn btn-outline-info" unless @suppress_links %>
        <% end %>
        <% if dyna_form.published? %>
          <%= button_to "Unpublish", {action: :unpublish, id: dyna_form.id, controller: :dyna_forms}, {class: "button-row btn btn-warning"} %>
        <% else %>
          <%= button_to "Publish", {action: :publish, id: dyna_form.id, controller: :dyna_forms}, {title: dyna_form.form_inputs.empty? ? "Form inputs are required to publish" : "", class: "button-row btn btn-success", disabled: dyna_form.form_inputs.empty?} %>
        <% end %>
        <%= button_to "#{dyna_form.locked ? 'Preview' : 'Form Builder'}", {action: :details, id: dyna_form.id, controller: :dyna_forms}, {class: "button-row btn btn-info"} unless @suppress_links %>
        <%= button_to "Delete", {action: :destroy, id: dyna_form.id, controller: :dyna_forms}, {class: "button-row btn btn-danger", method: :delete} %>
      <% else %>
        <%= link_to "Take Survey", take_survey_path(dyna_form), class: "btn btn-primary button-row", target: "_blank" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/dyna_forms/_dyna_form_with_inputs.html.erb
<%= turbo_frame_tag "user_dyna_form_window" do %>
  <div class="container py-5">
    <h2>Form Builder</h2>
  </div>
  <%= turbo_frame_tag dom_id(dyna_form) do %>
    <div class="card card-body">
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-body">
            <h4><%= dyna_form.title%></h4>
            <p>
              <%= dyna_form.description %>
            </p>
            <%= turbo_stream_from "#{dom_id(dyna_form)}_form_input_samples" %>
            <%= turbo_frame_tag "#{dom_id(dyna_form)}_form_input_samples" do %>
              <% dyna_form.form_inputs.each do |form_input| %>
                <%= render partial: "form_inputs/sample", locals: {form_input: form_input, submitted_form_response: SubmittedFormResponse.new(form_input_id: form_input.id), editing: dyna_form.published?} %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% unless dyna_form.locked? %>
        <div class="row py-5">
          <div class="col-lg-12">
            <div class="card card-body">
              <h4>Add inputs to DynaForm <%= dyna_form.title %></h4>
              <% form_input = FormInput.new(dyna_form_id: dyna_form.id, input_type_id: Current.ordered_input_types.first.id) %>
              <% submitted_form_response = SubmittedFormResponse.new(form_input: form_input) %>
              <%= render partial: "form_inputs/form", locals: {form_input: form_input, dyna_form: dyna_form, submitted_form_response: submitted_form_response} %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/dyna_forms/_form.html.erb
  <div class="card card-body" id="<%= dom_id(dyna_form)%>">
  <%= form_with(model: dyna_form) do |f| %>
    <%= render partial: "form_elements/text_field_input", locals: {obj: dyna_form, field: :title, form_obj: f} %>
    <%= render partial: "form_elements/text_area_input", locals: {obj: dyna_form, field: :description, form_obj: f} %>
    <div class="button-row-container">
      <%= f.submit "Save draft and start building", class: "btn btn-primary button-row" %>
    </div>
<% end %>
</div>

app/views/dyna_forms/_preview.html.erb
<%= turbo_frame_tag "user_dyna_form_window" do %>
  <div class="container py-5">
    <h2>Preview</h2>
  </div>
  <%= turbo_frame_tag dom_id(dyna_form) do %>
    <div class="card card-body">
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-body">
            <h4><%= dyna_form.title%></h4>
            <p>
              <%= dyna_form.description %>
            </p>
            <%= turbo_stream_from "#{dom_id(dyna_form)}_form_input_samples" %>
            <%= turbo_frame_tag "#{dom_id(dyna_form)}_form_input_samples" do %>
              <% dyna_form.form_inputs.each do |form_input| %>
                <div class="container py-5">
                  <%= render partial: "form_inputs/sample", locals: {form_input: form_input, submitted_form_response: SubmittedFormResponse.new(form_input_id: form_input.id), editing: true} %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/dyna_forms/_results.html.erb
<%= turbo_frame_tag "user_dyna_form_window" do %>
  <div class="container py-5">
    <h2>Results</h2>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% headers.each do |header| %>
          <th>
            <%= header[0] %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% submitted_data.each do |row| %>
        <tr>
          <% headers.each do |header| %>
            <td><%= row[header[1]] %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/dyna_forms/create.turbo_stream.erb
<%= turbo_stream.replace("new_dyna_form", partial: "dyna_forms/form", locals: {dyna_form: DynaForm.new}) %>
<%= turbo_stream.replace("user_dyna_form_window", partial: "dyna_forms/dyna_form_with_inputs", locals: {dyna_form: @dyna_form}) %>

app/views/dyna_forms/published_surveys.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Published surveys</h1>
  </div>
  <% @suppress_links = true %>
  <%= turbo_frame_tag "published_dyna_forms" do %>
    <%= render @dyna_forms %>
  <% end %>
</div>

app/views/dyna_forms/take_survey.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-4 col-center text-center">
      <div id="watch-container">
        <div class="spinner-border" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <div>
          Give us a few to prepare your survey...
        <div>
      </div>
    </div>
  </div>
</div>
<script>
  app.TriggerBuild("<%= @dyna_form.id%>", "<%= form_authenticity_token %>");
</script>