config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#index", as: "root"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete", as: "logout"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  post "/dyna_forms/:id/publish", to: "dyna_forms#publish", as: :dyna_form_publish
  post "/dyna_forms/:id/unpublish", to: "dyna_forms#unpublish", as: :dyna_form_unpublish
  post "/dyna_forms/:id/details", to: "dyna_forms#details", as: :dyna_form_details
  get "/dyna_forms/:id/take_survey", to: "dyna_forms#take_survey", as: :take_survey
  post "/dyna_forms/:id/results", to: "dyna_forms#results", as: :dyna_form_results
  get "/published_surveys", to: "dyna_forms#published_surveys", as: :published_surveys

  delete "form_inputs/:id", to: "form_inputs#destroy", as: :form_input_delete
  post "form_inputs/:id/edit",to: "form_inputs#edit", as: :form_input_edit

  post "submitted_forms/build_survey", to: "submitted_forms#build_survey"
  post "submitted_forms/:id/save_progress", to: "submitted_forms#save_progress", as: :submitted_form_response_save_progress
  resources :submitted_forms, only: [:show]

  resources :dyna_forms do
    resources :form_inputs, except: [:destroy]
    post 'form_inputs/sample', to: 'form_inputs#sample', as: "form_inputs_sample"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email,
    format: { with: URI::MailTo::EMAIL_REGEXP, message: "invalid"  },
    uniqueness: { case_sensitive: false },
    length: { minimum: 4, maximum: 254 },
    presence: true

  validates :password,
    presence: true,
    length: { minimum: 8, maximum: 254 }

  validates_confirmation_of :password
  validates_presence_of :password_confirmation, if: :password_digest_changed?

  has_many :sessions

  has_many :dyna_forms

  #
  # Checks if the session is valid for the user
  #
  # @param session_id [String] the uuid of the session
  #
  # @return [Boolean]
  #
  def has_valid_session?(session_id)
    sessions.valid.find_by(id: session_id).present?
  end

  #
  # Logs the user in by creating a new session
  #
  # @return [Session]
  #
  def login!
    Current.session = Session.create!(user: self, expires_at: 1.week.from_now)
    Current.user = Current.session.user
    Current.session
  end

  #
  # Logs the user out - can optionally expire all sessions for the user
  #
  # @param session_id [String] the uuid of the session
  # @param all_sessions [Boolean] optional bit for expiring all sessions - defaults to false
  #
  # @return [void]
  #
  def logout!(all_sessions: false)
    qry = all_sessions ? Current.user.sessions.valid : sessions.where(id: Current.session.id)
    qry.update_all(expires_at: Time.now)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in

  layout "application_no_nav"

  # signup_url
  def new
    @user ||= User.new
  end

  # create user and sign them in
  def create
    @user = User.create(user_create_params)
    if @user.save
      user_session = @user.login!
      session[:current_session_id] = user_session.id

      respond_to do |format|
        format.turbo_stream { redirect_to dashboard_url, target: "_top" }
      end
    else
      respond_to do |format|
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            @user,
            partial: "users/form",
            locals: {user: @user}
          )}
      end
    end
  end

  def user_create_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<%= turbo_frame_tag dom_id(@user), target: "_top" do %>
  <div class="card card-body">
    <%= form_for user, as: :user, url: signup_url do |f|%>
        <%= render partial: "form_elements/text_field_input", locals: {field: :email, obj: @user, form_obj: f} %>
        <%= render partial: "form_elements/password_field_input", locals: {field: :password, obj: @user, form_obj: f} %>
        <%= render partial: "form_elements/password_field_input", locals: {field: :password_confirmation, obj: @user, form_obj: f} %>
        <div class="button-row-container">
        <%= submit_tag "Create User", class: 'button-row btn btn-primary' %>
        </div>
    <%end%>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-4 col-center">
      <h2>Signup</h2>
      <%= render partial: "users/form", locals: {user: @user} %>
      <div class="text-center">
        Already have an account? <%= link_to "Log in ", login_url %>here!
      </div>
    </div>
  </div>
</div>