config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#index", as: "root"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete", as: "logout"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  post "/dyna_forms/:id/publish", to: "dyna_forms#publish", as: :dyna_form_publish
  post "/dyna_forms/:id/unpublish", to: "dyna_forms#unpublish", as: :dyna_form_unpublish
  post "/dyna_forms/:id/details", to: "dyna_forms#details", as: :dyna_form_details
  get "/dyna_forms/:id/take_survey", to: "dyna_forms#take_survey", as: :take_survey
  post "/dyna_forms/:id/results", to: "dyna_forms#results", as: :dyna_form_results
  get "/published_surveys", to: "dyna_forms#published_surveys", as: :published_surveys

  delete "form_inputs/:id", to: "form_inputs#destroy", as: :form_input_delete
  post "form_inputs/:id/edit",to: "form_inputs#edit", as: :form_input_edit

  post "submitted_forms/build_survey", to: "submitted_forms#build_survey"
  post "submitted_forms/:id/save_progress", to: "submitted_forms#save_progress", as: :submitted_form_response_save_progress
  resources :submitted_forms, only: [:show]

  resources :dyna_forms do
    resources :form_inputs, except: [:destroy]
    post 'form_inputs/sample', to: 'form_inputs#sample', as: "form_inputs_sample"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"

end

app/models/form_input.rb
class FormInput < ApplicationRecord
  belongs_to :dyna_form
  belongs_to :input_type

  has_many :submitted_form_responses

  validates :label, presence: true
  validate :has_additional_attributes?
  validate :form_is_unlocked?

  before_create :set_display_order

  before_update :form_is_unlocked?

  after_create_commit do
    dyna_form.form_inputs.reload

    broadcast_append_to("dyna_form_#{dyna_form.id}_form_input_samples",
      target: "dyna_form_#{dyna_form.id}_form_input_samples",
      partial: 'form_inputs/sample',
      locals: {form_input: self, submitted_form_response: SubmittedFormResponse.new(form_input_id: id)}
    )

    broadcast_replace_to "user_#{Current.user.id}_dyna_forms",
      target: "dyna_form_#{dyna_form.id}",
      partial: 'dyna_forms/dyna_form',
      locals: {dyna_form: self.dyna_form} if Current.user
  end
  after_destroy_commit do
    dyna_form.form_inputs.reload

    broadcast_remove_to("dyna_form_#{dyna_form.id}_form_input_samples",
      target: "form_input_#{id}_sample"
    )

    broadcast_replace_to "user_#{Current.user.id}_dyna_forms",
      target: "dyna_form_#{dyna_form.id}",
      partial: 'dyna_forms/dyna_form',
      locals: {dyna_form: self.dyna_form} if Current.user
  end

  #
  # Helper method for parsing additional attributes into a json struct
  #
  # @return [Array]
  #
  def parsed_additional_attributes
    current_attrs = additional_attributes || ''
    JSON.parse(current_attrs) rescue current_attrs.split(',')
  end

  #
  # Override default additional_attributes= to convert comma-separated into a santized array
  #
  # @retiurn [void]
  #
  def additional_attributes=(val = '')
    super val.split(',').map {|v| v.strip }.join(',')
  end

  private

  def has_additional_attributes?
    return unless input_type.allows_additional_attributes?

    self.errors.add(:additional_attributes, "required for select option, checkbox, or radio select") unless additional_attributes.present?
  end

  def form_is_unlocked?
    self.errors.add("DynaForm", "is locked, further changes are not permitted") if self.dyna_form.locked
  end

  def set_display_order
    dyna_form.form_inputs.reload
    assign_attributes(display_order: dyna_form.form_inputs.length + 1)
  end
end

app/controllers/form_inputs_controller.rb
class FormInputsController < ApplicationController
  before_action :redirect_if_not_logged_in, :set_request_objects

  def create
    @form_input = FormInput.new(form_input_params)
    @form_input.dyna_form_id = params[:dyna_form_id]
    @submitted_form_response = SubmittedFormResponse.new(form_input: @form_input)
    respond_to do |format|
      if params[:sample]
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "new_form_input_sample",
            partial: "form_inputs/sample",
            locals: {form_input: @form_input, submitted_form_response: @submitted_form_response}
          )}
      elsif @form_input.save
        @form_input = FormInput.new(input_type_id: Current.ordered_input_types.first.id)
        @submitted_form_response = SubmittedFormResponse.new(form_input: @form_input)
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "new_form_input",
            partial: "form_inputs/form",
            locals: {form_input: @form_input, submitted_form_response: @submitted_form_response, dyna_form: @dyna_form}
          )}
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "new_form_input",
            partial: "form_inputs/form",
            locals: {form_input: @form_input, submitted_form_response: @submitted_form_response, dyna_form: @dyna_form}
          )}
      end
    end
  end

  def update
    @form_input.assign_attributes(form_input_params)
    @form_input.dyna_form_id = params[:dyna_form_id]
    respond_to do |format|
      if params[:sample]
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "form_input_#{@form_input.id}_sample",
            partial: "form_inputs/sample",
            locals: {form_input: @form_input, submitted_form_response: @submitted_form_response, editing: true}
          )}
      elsif @form_input.save
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "form_input_#{@form_input.id}",
            partial: "form_inputs/sample",
            locals: {form_input: @form_input, submitted_form_response: @submitted_form_response, dyna_form: @dyna_form}
          )}
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "form_input_#{@form_input.id}",
            partial: "form_inputs/form",
            locals: {form_input: @form_input, submitted_form_response: @submitted_form_response, dyna_form: @dyna_form, editing: true}
          )}
      end
    end
  end

  def edit
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          "form_input_#{@form_input.id}_sample",
          partial: "form_inputs/form",
          locals: {dyna_form: @form_input.dyna_form, form_input: @form_input, submitted_form_response: @submitted_form_response, editing: true}
        )
      }
    end
  end

  def destroy
    @form_input = Current.user.form_inputs.find(params[:id])
    @form_input.destroy
  end

  private
  def form_input_params
    params.require(:form_input).permit(:label, :helper_text, :input_type_id, :required, :additional_attributes, :display_order)
  end

  def set_request_objects
    @form_input = FormInput.find_by(id: params[:id])
    @dyna_form = DynaForm.find_by(id: params[:dyna_form_id])
    @submitted_form_response = SubmittedFormResponse.new(form_input: @form_input) if @form_input
  end
end

app/views/form_inputs/_form.html.erb
<% editing ||= false %>
<%= turbo_frame_tag dom_id(form_input) do %>
  <%= form_with(model: [dyna_form, form_input], id: dom_id(form_input)) do |f| %>
    <%= render partial: "form_elements/text_field_input", locals: {obj: form_input, field: :label, form_obj: f} %>
    <%= render partial: "form_elements/text_area_input", locals: {obj: form_input, field: :helper_text, form_obj: f} %>
    <div class="row">
      <div class="col-sm-7">
        <h6>Preview new input</h6>
        <%= render partial: "form_inputs/sample", locals: {form_input: form_input, submitted_form_response: submitted_form_response, editing: editing} %>

      </div>
      <div class="col-sm-5">
        <%= render partial: "form_elements/select_input", locals: {obj: form_input, field: :input_type_id, form_obj: f, options_for_select: Current.ordered_input_types.map { |input_type| [input_type.label, input_type.id] }, on_change: 'javascript:window.toggleAdditionalAttributes()'} %>
        <%= render partial: "form_elements/check_box_input", locals: {obj: form_input, field: :required, form_obj: f} %>
        <%= render partial: "form_elements/text_field_input", locals: {obj: form_input, field: :additional_attributes, form_obj: f, disabled: !form_input.input_type.allows_additional_attributes?, hidden: !form_input.input_type.allows_additional_attributes?} %>
      </div>
    </div>
    <div class="button-row-container">
      <%= f.button "Update preview", name: 'sample', value: true, class: 'button-row btn btn-outline-primary' %>
      <%= f.submit "Save", class: 'button-row btn btn-primary' %>
    </div>
    </div>
  <% end %>
<% end %>

app/views/form_inputs/_sample.html.erb
<% editing ||= false %>
<%= turbo_frame_tag "#{dom_id(form_input)}_sample" do %>
  <div class="container py-5">
    <%= render partial: "submitted_form_responses/#{form_input.input_type.ruby_klass.downcase}", locals: {sample: true, submitted_form_response: submitted_form_response} %>
    <% if form_input.persisted? && !editing %>
      <div class="button-row-container">
        <%= button_to "Delete", form_input_delete_path(form_input), {method: :delete, class: 'button-row btn btn-danger'} %>
        <%= button_to "Edit", form_input_edit_path(form_input), {method: :post, class: 'button-row btn btn-outline-primary'} %>
      </div>
    <% end %>
  </div>
<% end %>