config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#index", as: "root"

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#delete", as: "logout"

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"

  post "/dyna_forms/:id/publish", to: "dyna_forms#publish", as: :dyna_form_publish
  post "/dyna_forms/:id/unpublish", to: "dyna_forms#unpublish", as: :dyna_form_unpublish
  post "/dyna_forms/:id/details", to: "dyna_forms#details", as: :dyna_form_details
  get "/dyna_forms/:id/take_survey", to: "dyna_forms#take_survey", as: :take_survey
  post "/dyna_forms/:id/results", to: "dyna_forms#results", as: :dyna_form_results
  get "/published_surveys", to: "dyna_forms#published_surveys", as: :published_surveys

  delete "form_inputs/:id", to: "form_inputs#destroy", as: :form_input_delete
  post "form_inputs/:id/edit",to: "form_inputs#edit", as: :form_input_edit

  post "submitted_forms/build_survey", to: "submitted_forms#build_survey"
  post "submitted_forms/:id/save_progress", to: "submitted_forms#save_progress", as: :submitted_form_response_save_progress
  resources :submitted_forms, only: [:show]

  resources :dyna_forms do
    resources :form_inputs, except: [:destroy]
    post 'form_inputs/sample', to: 'form_inputs#sample', as: "form_inputs_sample"
  end

  get "/dashboard", to: "dashboard#index", as: "dashboard"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current

  def index
  end

  private
  def set_current
    Current.session = Session.find_by(id: session[:current_session_id]) if session.include?(:current_session_id)
    Current.user = Current.session&.user
  end

  def redirect_if_not_logged_in
    redirect_to login_url unless Current.user
  end

  def redirect_if_logged_in
    redirect_to root_url if Current.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_message.html.erb
<%= turbo_frame_tag "flash_message" do %>
  <% message ||= '' %>
  <% status ||= "success" %>
  <% if message.present? %>
    <div id="flash-message-container">
      <main id="flash-message-content">
        <div class="flash-message-controls">
          <a class="clickable" onclick="app.FlashMessageControls.closeFlash()">
            <%= icon("x-lg") %>
          </a>
        </div>
        <div class="flash-message-content">
          <div class="flash-message text-center is-<%= status %>">
            <%= message %>
          </div>
        </div>
      </main>
    </div>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer>
  <div class="container my-5">
  </div>
</footer>

app/views/application/_nav_item.html.erb
<li class="nav-item <%= request.fullpath == href ? 'active' : '' %>">
  <a class="nav-link" href="<%= href %>"><%= label %></a>
</li>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand">DynaForm</a>
      <ul class="navbar-nav me-auto mt-2 mt-lg-0">
        <%= render partial: "nav_item", locals: {href: published_surveys_path, label: "Published Surveys"} %>
        <% if Current.user %>
          <%= render partial: "nav_item", locals: {href: dashboard_path, label: "My Dashboard"} %>
        <% end %>
      </ul>
      <div class="navbar">
        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= button_to "Logout", logout_url, class: 'form-control', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item px-3">
            <%= button_to "Login", login_url, class: 'form-control nav-item', method: :get %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign up", signup_url, class: 'form-control nav-item', method: :get %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/application/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Welcome to DynaForm!</h1>

    <div class="container">
      <p>
        DynaForm is a utility for creating and building dynamic forms while providing a clean interface to capture and read the data. To get started, head over to the
        <%= link_to 'sign up', signup_url %> if you don't yet have an account. Or, check out the <%= link_to "published surveys", published_surveys_url %> to see if there are any surveys awaiting data collection.
      </p>
    </div>
    <div class="container">
      <!--
      <h3>How does it work?</h3>
      <p>
        Anyone with an active user account can manager their forms through their personal dashboard. From the dashboard, users can
        create drafts, build forms, publish/unpublish their content, and see results of published content.
      </p>
      <p>
        To get started:
        <ol>
          <li>Create an account (or login if you have one already).</li>
          <li>Navigate to <%= link_to "your dashboard", dashboard_url %></li>
          <li>Enter a title and description for a new form.</li>
          <li>Once the draft is saved the form should be loaded into the form builder.</li>
          <li>In the form build, add inputs to the form. Inputs do require a label at minimum.</li>
          <li>Some input types (checkbox and option selects will require a list of items to be presented to the individual taking the survey.</li>
          <li>Once you are happy with the results select Publish.</li>
          <li><b>Important:</b> Once published, DynaForms's and their respective inputs cannot be altered or update. This is intentional to ensure the collected data aligns with the information presented to the user when they took the survey.</li>
          <li>There is no rush to publish. If you need time gradually build out the form you can always come back to your dashboard and pickup where you left off</li>
          <li>There is no limit on the number of published or unpublished forms you can have at a time.</li>
          <li>Once published, the survey will show on the <%= link_to "Published Surveys", published_surveys_url %> page.</li>
          <li>Only site visitors or users that did not create the DynaForm are presented with the option to take the survey.</li>
          <li>Results for a survey can be seen on <%= link_to "your dashboard", dashboard_url %> by selecting See Results for a particular survey. This is only available once a survey is published.</li>
        </ol>
      </p>
      -->
    </div>
  </div>
</div>